### ISSUE TITLE
Multiple timeout values?

### ISSUE THREAD

**Issue by richb-hanover** [irino/softflowd#1]
@irino @SysError956 - I wonder whether it's possible to supply two timeout values for softflowd. I would like to use these two values:

* general=15s - to flush out flows that complete (no traffic after 15 sec) relatively quickly
* maxlife=60s - to provide continuing updates for long-running streams

1. Does softflowd support multiple timeout values?
2. Is it possible to supply both on the command line, e.g., `... -t general=15s -t maxlife=60s ...`
3. How do you specify these in the /etc/config/softflowd file?

Many thanks!

**Comment by irino** [comment]
It works with  `... -t general=15s -t maxlife=60s ...` option.
