### ISSUE TITLE
out-of-tree symlink COPYING

### ISSUE THREAD

**Issue by cbiedl** [irino/softflowd#14]
Greetings,
Debian maintainer for softflowd speaking, thank you for continuing the work on softflowd.
Now Debian's packaging linter "lintian" reported a few issues about the the upstream tar ball, so bringing them here: The file COPYING is a symlink to /usr/share/automake-1.15/COPYING, i.e. out of tree, probably by mistake then this doesn't make sense. Perhaps replace it with a file?

**Comment by irino** [comment]
Thank you for reporting.
I made a symlink from LICENSE to COPYING.
