### ISSUE TITLE
[patch] install in sbin again

### ISSUE THREAD

**Issue by cbiedl** [irino/softflowd#16]
Hello,
previously, the generated binaries softflowctl and softflowd were installed in /usr/sbin (more precisely: $prefix/sbin). This changed to /usr/bin, very likely in 2e18e6 ("Use automake and update manpage")
In my opinion sbin is the right place, so please store the old behaviour. Trivial patch.
{{{
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,4 +1,4 @@
-bin_PROGRAMS = softflowd softflowctl
+sbin_PROGRAMS = softflowd softflowctl
 COMMON = common.h convtime.h treetype.h sys-tree.h\
   convtime.c strlcpy.c strlcat.c closefrom.c daemon.c
 if ENABLE_LEGACY
}}}

**Comment by irino** [comment]
Thank you for report. I changed.
