### ISSUE TITLE
"ntopng" export with tracking level "ether" - wrong MAC adresses

### ISSUE THREAD

**Issue by vovan69** [irino/softflowd#20]
Hello,

First of all, thanks a lot for implementing ntopng export option and maintaining this fork!
If softflowd is used with following options "-v ntopng -T ether" MAC addresses displayed in the ntopng web gui in dec instead hex. For example MAC address xx:xx:xx:xx:27:3a displayed as xx:xx:xx:xx:39:58.

Regards,
Vlad.

**Comment by irino** [comment]
I fixed.
Please try and report.

**Comment by vovan69** [comment]
> I fixed.
> Please try and report.

Now it works as expected. Thanks you!
