### ISSUE TITLE
softflowd does not report direction and if_name in v9 which is important metrics

### ISSUE THREAD

**Issue by pwp333** [irino/softflowd#22]
softflowd does not report direction and if_name in v9 which is important metrics

DIRECTION 61
IF_NAME 82

Could we add these?

**Comment by irino** [comment]
I added these IEs on the latest commit ead968d2843019dfb9e686f1c114833be761b32c .

**Comment by pwp333** [comment]
Thanks a lot Hitoshi! We appreciate your help!

**Comment by pwp333** [comment]
Hi Hitoshi, could you please help to port this ipfix change over to netflow9.c? Thanks a lot.

61:
- :uint8
- :direction

252:
- :uint32
- :ingressPhysicalInterface

253:
- :uint32
- :egressPhysicalInterface

**Comment by irino** [comment]
I have no idea to lookup interface name when "any" is specified, because pcap_dispatch function doesn't have interface information.
I think it is better to run each softflowd process for each interface.

**Comment by pwp333** [comment]
Thanks Hitoshi for the info. Does softflowd cache flow in memory? Was worried if multiple softflowd process can take much memory.

**Comment by irino** [comment]
Yes, cache is on memory. If you worry the amount of memory, I think it is better to use limitation of number of flows by -m option.

**Comment by jbhardman** [comment]
Probably something I should know how it works, but is there anyway to get this update into the version of softflowd distributed in the pfsense package manager? There is no direction there for IPFIX and I would really like to get that.
Thanks!
@irino

**Comment by jbhardman** [comment]
I compiled from current source on FreeBSD and replaced the two binaries on my pfSense host that came with the package manager. This now includes Direction in the template. Thanks.
