### ISSUE TITLE
protocol number is missing in v9/IPFIX for ICMP flow

### ISSUE THREAD

**Issue by pwp333** [irino/softflowd#31]
[v5]
  "netflow" => {
                  "protocol" => 1,
                   "version" => 5,
                 "engine_id" => 0,
             "ipv4_next_hop" => "0.0.0.0",
                   "in_pkts" => 12,
               "engine_type" => 0,
               "l4_dst_port" => 0,
                  "src_mask" => 0,
               "output_snmp" => 0,
            "first_switched" => "2020-07-13T22:07:34.281Z",
                  "dst_mask" => 0,
             "ipv4_dst_addr" => "172.16.0.42",
                  "in_bytes" => 1008,
        "sampling_algorithm" => 0,
         "sampling_interval" => 0,
             "ipv4_src_addr" => "8.8.8.8",
             "last_switched" => "2020-07-13T22:07:45.296Z",
              "flow_records" => 2,
                    "src_as" => 0,
                    "dst_as" => 0,
                   "src_tos" => 0,
              "flow_seq_num" => 482,
                "input_snmp" => 0,
                 "tcp_flags" => 0,
               "l4_src_port" => 0
    }

[v9]

  "netflow" => {
                "output_snmp" => 0,
                    "src_tos" => 0,
             "first_switched" => "2020-07-13T22:11:02.976Z",
               "flow_seq_num" => 416,
                 "flowset_id" => 1025,
                  "icmp_type" => 2048,
                    "if_name" => "eth0",
        "ip_protocol_version" => 4,
                    "version" => 9,
                    "in_pkts" => 12,
              "ipv4_dst_addr" => "8.8.8.8",
                  "direction" => 1,
                   "in_bytes" => 1008,
                 "input_snmp" => 0,
              "ipv4_src_addr" => "172.16.0.42",
              "last_switched" => "2020-07-13T22:11:13.990Z",
            "flow_end_reason" => 2
    },

**Comment by pwp333** [comment]
Pull request here
https://github.com/irino/softflowd/pull/32

**Comment by irino** [comment]
Your PR is Merged. Thanks.
