### ISSUE TITLE
netflow v9 reporting incorrect timestamp in message headers

### ISSUE THREAD

**Issue by traetox** [irino/softflowd#37]
Softflowd Version 0.9.9 is exporting an incorrect timestamp in the message header field when exporting Netflow V9.

If configured to export IPFIX (v10) the msg header timestamp field is correct.

I validated that the current time on the host box is correct, the field appears to be populated with an integer uptime value, rather than the the unix timestamp as indicated by the Cisco Spec: https://www.cisco.com/en/US/technologies/tk648/tk362/technologies_white_paper09186a00800a3db9.html

![Screenshot from 2020-12-18 11-55-50](https://user-images.githubusercontent.com/1326392/102650477-3a725200-4128-11eb-9e59-df5b0e4d46e8.png)

**Comment by irino** [comment]
I can not reproduce this issue on master branch when packet is captured from interface. please use latest source code on master.
