### ISSUE TITLE
version 1.0.0 crashes on openwrt 22.03 release

### ISSUE THREAD

**Issue by laoshaw** [irino/softflowd#44]
not sure if this is the right place to report, if not please ignore

`Sun Oct 16 19:54:36 2022 daemon.info procd: Instance softflowd::instance1 s in a crash loop 8 crashes, 78 seconds since last crash`

is there a debug flag I can turn on to assist debugging?

**Comment by irino** [comment]
This log message is not softflowd's message. I assume it is openwrt's log message. Please report to openwrt's community.
