### ISSUE TITLE
Please remove cvs/hg cruft

### ISSUE THREAD

**Issue by cbiedl** [irino/softflowd#5]
Severity: whishlist

Hello,

there are still some files around from CVS (.cvsignore) and Mercurial (.hg*) times. They can safely be removed. If however you could create tags in git based on the ones .hgtags, I'd be glad.

**Comment by irino** [comment]
I deleted .cvsignore in https://github.com/irino/softflowd/commit/c9038bfa42bf21b320bc58c1c9b5519d461d972c .
I added tags for each version.
I think this repository does not have any Mercurial files.
