### ISSUE TITLE
How can we configure softflowd to enable exporter for Netflow V9 format?

### ISSUE THREAD

**Issue by syslabtech** [irino/softflowd#50]
Hello Team,

We have used cloudflare/goflow docker container image and set up it in our Kubernetes to collect Netflow data. 

When we start our Netflow exporter (softflowd) in PfSense , we see logs into goflow container but it looks that it is not in to the Netflow V9 format.

Our Netflow collector is working properly issue with exporter softflowd.

How can we configure softflowd to enable expoter for Netflow V9 format?
Can you please help us here?

**Comment by irino** [comment]
softflowd has -v option. Please specify -v 9.
I'm not sure about PfSense configuration. Please ask in PfSense community.
