### ISSUE TITLE
sotflowd sending the same flow sometimes, twice, and sometimes three times

### ISSUE THREAD

**Issue by mcury1985** [irino/softflowd#51]
I'm sending Netflow data from pfSense (softflowd), to a Graylog server.
I'm using Graylog to sum the amount of data passed through an interface, to get a list of top Talkers in a determined time frame.

I noticed that the sum in Graylog is not matching the amount of data because the same flow is sent sometimes twice, sometimes three times.
What differs from these sent flows from softflowd to Graylog are the **nf_input_snmp, nf_snmp_output and nf_flow_packet_id** fields.

I reported it too as bug in redmine pfsense, https://redmine.pfsense.org/issues/14747 because I'm not sure if this is a bug with softflowd or a bug with the pfsense softflowd package.

Here is an example of a flow that softflowd sent three times to Graylog server:
![clipboard-202309041446-etky4](https://github.com/irino/softflowd/assets/79334977/18265d54-e92a-421c-8ba0-8a9e2ea0cf10)

Is there a way to force the flow to be sent once ? I can't make Graylog search to check a single snmp input since it is complete random..

Thanks

**Comment by mcury1985** [comment]
It seems that the problem is related to VLAN interfaces.
I've been doing some tests and if you set softflowd to collect only from non VLAN interfaces, the problem doesn't happen.

These two interfaces are making softflowd to act in a weird way.
igc1.10
igc1.20

In case you need more details, just let me know.
Thanks.

**Comment by irino** [comment]
I don't know pfsense's detail
If vlan tracking option (-T vlan) is enabled, the flows on different vlan are distinguished as different flow even if 5 tupples in IP packets are same.
I don't know what options of softflowd is specfied by pfSense. Please ask pfSense community.

**Comment by mcury1985** [comment]
I think the problem happens when you listen on the parent interface along with VLANs inside of it.

MGMT - igc1
WIFI - igc1.10
LAN - igc0

See, connections from WIFI igc1.10 to LAN igc0, were being collected sometimes three times, sometimes two, completely random..

As soon as I disabled the parent interface (igc1), and now listening only on igc1.10 and igc0, I'm not getting the same netflow data sent three times, only twice if the traffic is intervlan (which is expected since pfsense will collect from both interfaces).

**Comment by mcury1985** [comment]
Thank you irino for the insight on this matter.
I'll keep collecting from igc0 and igc1.10 only and use the workaround (filter by nf_input_snmp:1 for intervlan traffic) for now.

Much appreciated.
