### ISSUE TITLE
Overflow of flowStartSysUpTime and flowEndSysUpTime

### ISSUE THREAD

**Issue by HolgerHees** [irino/softflowd#52]
Hi,

I have an issues with calculating flow times using systemInitTimeMilliseconds, flowEndSysUpTime and flowStartSysUpTime.

Every 49 days, I have to restart softflowd to avoid a number overflow.

e.g. 

**systemInitTimeMilliseconds** is sending the milliseconds since last softflow restart (device init time). If I add  **flowStartSysUpTime** (relative timestamp in milliseconds related to **systemInitTimeMilliseconds**), I get the time of the flow event. 

The Problem is that **flowStartSysUpTime** and **flowEndSysUpTime** are unsigned 32 bit numbers. That means thay can handle a maximum of 49 days, which are 4294967295 milliseconds.

I'm not a netflow expert, so maybe I interpret something wrong

I'm using softflowd version 1.0.0 which comes with the latest openwrt release

**Comment by irino** [comment]
I think that a quick solution is using "-A" option which represents absolute time if your collector can receive IEs between 150 and 157 (Ref. https://www.iana.org/assignments/ipfix/ipfix.xhtml)

**Comment by HolgerHees** [comment]
thanks a lot for the hint
