### ISSUE TITLE
netflow failled !Ignored packets: 4587626 (4587626 non-IP, 0 too short)

### ISSUE THREAD

**Issue by 1171782907** [irino/softflowd#53]
/usr/local/sbin/softflowd -r test.pcap  -n 127.0.0.1:9991 -s 1 -v 9 -D -t maxlife=1
softflowd v0.9.9 starting data collection
Exporting flows to [127.0.0.1]:osm-oev
Shutting down after pcap EOF
Shutting down on user request
Starting expiry scan: mode -1
Finished scan 0 flow(s) to be evicted
Number of active flows: 0
Packets processed: 0
Fragments: 0
Ignored packets: 4587626 (4587626 non-IP, 0 too short)
Flows expired: 0 (0 forced)
Flows exported: 0 in 0 packets (0 failures)

**Comment by irino** [comment]
I cannot tell suitable advice because I don't know your test.pcap.
