### ISSUE TITLE
How to configure to send the interface id , ex: in_if ,out_if interface id

### ISSUE THREAD

**Issue by bj1116** [irino/softflowd#55]
How to configure to send the interface id , ex: in_if ,out_if interface id.
https://github.com/netsampler/goflow2/blob/main/docs/protocols.md

![image](https://github.com/user-attachments/assets/78a18f08-c694-42b0-b140-e91a99149312)

**Comment by irino** [comment]
You can specify interface index manually using -i option. 
please specify if_index:if_name (e.g, 10:eth1) as -i option variable.

**Comment by bj1116** [comment]
ok , tks .
