### ISSUE TITLE
segfault upon emtpy interface string

### ISSUE THREAD

**Issue by cbiedl** [irino/softflowd#6]
`strtok` in softflowd.c:1787, introduced in commit cdf7ae1 "Using strtok instead of strsep in environments which does not have strsep" might return NULL, something `atoi` in line 1790 cannot handle.

As a result:
```
$ ./softflowd  -i ''
Segmentation fault
```
Please add a sanity check.

**Comment by irino** [comment]
It is fixed in https://github.com/irino/softflowd/commit/ddf7f5b9d30f54b58a3911d95041423504f499ea ,

**Comment by irino** [comment]
I fixed this bug in https://github.com/irino/softflowd/commit/bbd0685d69236844138f96df387a31506d641d0d .
