### ISSUE TITLE
TOS exporting

### ISSUE THREAD

**Issue by stephanbuys** [irino/softflowd#8]
So great to see activity on this repo, was not sure the project was still active - so didn't bother reporting.

When generating flows we have not been able to export the TOS fields. A quick look at the code shows TOS fields are supposed to be exported but they are always 0 in our tests.

**Comment by irino** [comment]
Could you give me a sample pcap for a test?

**Comment by stephanbuys** [comment]
I will request one, and send through ASAP - thanks.

**Comment by irino** [comment]
I tested using IPv4 ssh traffic which contains TOS 0x10. The exported NetFlow traffic generated by softflowd contains non zero TOS.
